### ISSUE TITLE
görüntülerin saklanması için entegrasyon yada db çözümü yapılması

### ISSUE THREAD

**Issue by erogluefe** [rumeysaozaydin/auction#27]
iki seçenek var ya db de tutulacak yada Amazon S3, Firebase gibi bir servis kullanılacak. En yaygın olanı s3 entegrasyonu ama direk db üzerinde de tutabiliriz

amazon:
https://aws.amazon.com/tr/s3/

firebase:
https://firebase.google.com/docs/storage

db:
https://www.baeldung.com/java-db-storing-files

https://medium.com/@rameez.s.shaikh/upload-and-retrieve-images-using-spring-boot-angular-8-mysql-18c166f7bc98

bana en mantıklı ve ileride de yarayacak s3 geliyor .

**Comment by ahmetserdargurbuz** [comment]
hangisinin entegrasyonu daha kolay ve hızlıysa o şekilde ilerleyelim derim

**Comment by ahmetserdargurbuz** [comment]
Öbür taraftaki issue db ile çözüldüyse burayı kapatalim.
